[install] Verify env vars set before installing packages

diff --git a/bin/install_packages b/bin/install_packages
--- a/bin/install_packages
+++ b/bin/install_packages
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z $XDG_CONFIG_HOME || -z $XDG_CACHE_HOME || -z $XDG_DATA_HOME ]]; then
+    echo 'XDG environment variables not set. Aborting...';
+    exit 1;
+fi
+
 mkdir -p "$XDG_CONFIG_HOME"
 mkdir -p "$XDG_CACHE_HOME"
 mkdir -p "$XDG_DATA_HOME"
@@ -12,10 +17,12 @@ if [[ ! -e $XDG_DATA_HOME/git-prompt.sh ]]; then
 fi
 
 # FZF
+echo 'Installing FZF...'
 git clone https://github.com/junegunn/fzf.git "$XDG_DATA_HOME/fzf"
 "$XDG_DATA_HOME/fzf/install" --all --no-update-rc
 mv ~/.fzf.bash "$XDG_DATA_HOME/fzf/fzf.bash"
 mv ~/.fzf.zsh "$XDG_DATA_HOME/fzf/fzf.zsh"
+echo 'Done installing FZF.'
 
 # MacOS
 if [[ $(uname -s) = 'Darwin' ]]; then
